
name: Docker Build

on:
  pull_request:
    branches: 
      - deploy
    types: [closed]
    
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event.pull_request.merged }} == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t metrics_collector:latest .

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push Docker image to ghcr.io
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/metrics_collector
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag metrics_collector $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION